# .github/workflows/update.yml
name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get default branch
        id: branch
        run: |
          echo "branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          echo "" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: keep alive" || exit 0
          git push

      - name: Retrigger
        if: success()
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Keep Alive
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.branch.outputs.branch }}
